[OPS-7688] core security update
UN-OCHA/gho-site pull request #248
Opened 2021-08-17 14:47 UTC by lazysoundsystem

https://humanitarian.atlassian.net/browse/OPS-7688

2021-08-17 14:48 UTC, lazysoundsystem commented
@rupl just checking that the styling changes already in dev are all okay to go.

2021-08-18 07:51 UTC, rupl commented on config/block.block.searchform.yml
> +status: true
@lazysoundsystem the only issue is that I enabled search via config and until we get sign-off on how dev looks, I don't think it's appropriate to deploy.

@emmajane do you agree that we should disable search before deploying this work to prod?

2021-08-18 07:52 UTC, rupl commented on config/block.block.searchform.yml
> +status: true
(I picked this line because I think changing `true` to `false` is enough to hide the block and avoid exposing search to the public)

2021-08-18 07:56 UTC, emmajane commented on config/block.block.searchform.yml
> +status: true
tl;dr: it should not display. If it's enabled but not showing up I guess that's okay if it's easier to get the security update out. But it should not display. (I said that bit twice, right? :) )

We're still a few weeks away from wanting to enable search on prod. I have a small preference for keeping it disabled on prod until we're ready for it. I have a large preference for it not displaying in the main menu until it's been approved by the team.

2021-08-18 08:03 UTC, rupl requested changes
Based on @emmajane comments I am requesting changes and assigning myself this PR until `develop` is updated with necessary config to do the following:

- Disable search entirely.
- Make sure the Block that appears in the main nav is not showing up.

2021-08-18 09:19 UTC, rupl commented
With the latest commits to `develop` I believe this is ready.

2021-08-18 09:19 UTC, rupl approved these changes

2021-08-18 09:56 UTC, merged