GHO-12: Appeals tags
UN-OCHA/gho-site pull request #35
Opened 2020-10-19 11:12 UTC by rupl

# GHO-12

PR contains config/theming for Appeals tags. They're attached to Article nodes but I think the template names I chose to overrode mean it will work anywhere (as paragraph, on different content types, etc)

The colors are stored in the component-specific CSS and they came straight off of hum-insight.info production. 

## Testing

```sh
$ drush cim
$ drush cr
```

After importing config, create taxonomy terms with the following titles: HRP, FA, RRP, Other — they should automatically pick up the appropriate colors and appear like so:

![image](https://user-images.githubusercontent.com/254753/96442931-2be0ea80-120c-11eb-8793-da22fae15ffe.png)

I used similar styles to some of the other flex components (negative margin on container) to ensure that RTL works out of the box. The tags themselves are English only and not translatable. I used the [Arabic-language 2020 GHO PDF](https://www.humanitarianresponse.info/sites/www.humanitarianresponse.info/files/documents/files/gho-2020_ar_web.pdf) (see page 28) as the basis for my decision, which uses latin-character tags amongst the otherwise arabic content.

2020-10-19 15:22 UTC, rupl commented
After taking a second look at the Arabic PDF linked above, I've allowed translation on the extended name field. The PDF lists translations at the bottom of page 28 but since it's no trouble to do that inline, we can offer title attributes once the tag gets translated. We will instruct folks not to alter the main tag name (e.g. `HRP`)

Here's that it looks like on mouse hover:

<img width="436" alt="Screen Shot 2020-10-19 at 16 48 18" src="https://user-images.githubusercontent.com/254753/96471427-9fe0ba00-122f-11eb-93fe-00c069c7ca01.png">

2020-10-20 07:34 UTC, orakili requested changes
Looks good, just a tiny change to make in the template (see comment).

2020-10-20 07:34 UTC, orakili commented on html/themes/custom/common_design_subtheme/templates/taxonomy/taxonomy-term--appeals.html.twig
> +<div{{ attributes.addClass(classes, 'gho-appeals-tag--' ~ tagname|lower) }} title="{{ content.field_appeal_extended|render|striptags|trim }}">
Rather than `tagname|lower`, better to use `tagname|clean_class` which changes the text to lower but also ensures it's suitable to use as a class.

Also are the `|render|striptags` necessary on the `name` necessary?

2020-10-20 07:51 UTC, rupl commented on html/themes/custom/common_design_subtheme/templates/taxonomy/taxonomy-term--appeals.html.twig
> +<div{{ attributes.addClass(classes, 'gho-appeals-tag--' ~ tagname|lower) }} title="{{ content.field_appeal_extended|render|striptags|trim }}">
nice tip. I have seen `clean_class` but didn't think to use it.

yes on the render and strip tags. At least in the sense that it's the only combo I could find that totally removes all whitespace to make the value suitable as a `title` attribute.

2020-10-20 09:26 UTC, rupl commented
Added the fifth color per our meeting/demo with Edgar today:

![image](https://user-images.githubusercontent.com/254753/96567415-0664e700-12c7-11eb-8ad7-77fce22ad0e1.png)

2020-10-20 09:29 UTC, orakili approved these changes
Looks good. Thanks!

2020-10-20 10:17 UTC, merged